### ISSUE TITLE
Feature request: Adjusting speed

### ISSUE THREAD

**Issue by karmanyaahm** [bernikr/windmill#1]
It would be really nice if there's some way to skip forward or speed up some of the more chaotic simulations.

**Comment by bernikr** [comment]
I've implemented a basic speed control. Unfortunately the code in this project is really bad since I have written it in a few hours when I was still new to coding. Because of that setting speeds too slow or too fast cause the thing to break completely. (see #2)
Therefore I have chosen to limit the speed in the range of 25%-1000% as that doesn't seem to cause problems.
